language: node_js
node_js:
  - "0.6"

# whitelist
branches:
  only:
    - test_travisci

install: npm install esprima
script: "node nodejs_geor_rules.js ./extractorapp/src/main/webapp/app/js/GEOR_Lang/"
